/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialsMaterialIdPlantIdRouteImport } from './routes/materials.$materialId.$plantId'

const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsMaterialIdPlantIdRoute =
  MaterialsMaterialIdPlantIdRouteImport.update({
    id: '/$materialId/$plantId',
    path: '/$materialId/$plantId',
    getParentRoute: () => MaterialsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/materials': typeof MaterialsRouteWithChildren
  '/recommendations': typeof RecommendationsRoute
  '/materials/$materialId/$plantId': typeof MaterialsMaterialIdPlantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/materials': typeof MaterialsRouteWithChildren
  '/recommendations': typeof RecommendationsRoute
  '/materials/$materialId/$plantId': typeof MaterialsMaterialIdPlantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/materials': typeof MaterialsRouteWithChildren
  '/recommendations': typeof RecommendationsRoute
  '/materials/$materialId/$plantId': typeof MaterialsMaterialIdPlantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/copilot'
    | '/materials'
    | '/recommendations'
    | '/materials/$materialId/$plantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/copilot'
    | '/materials'
    | '/recommendations'
    | '/materials/$materialId/$plantId'
  id:
    | '__root__'
    | '/'
    | '/copilot'
    | '/materials'
    | '/recommendations'
    | '/materials/$materialId/$plantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CopilotRoute: typeof CopilotRoute
  MaterialsRoute: typeof MaterialsRouteWithChildren
  RecommendationsRoute: typeof RecommendationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$materialId/$plantId': {
      id: '/materials/$materialId/$plantId'
      path: '/$materialId/$plantId'
      fullPath: '/materials/$materialId/$plantId'
      preLoaderRoute: typeof MaterialsMaterialIdPlantIdRouteImport
      parentRoute: typeof MaterialsRoute
    }
  }
}

interface MaterialsRouteChildren {
  MaterialsMaterialIdPlantIdRoute: typeof MaterialsMaterialIdPlantIdRoute
}

const MaterialsRouteChildren: MaterialsRouteChildren = {
  MaterialsMaterialIdPlantIdRoute: MaterialsMaterialIdPlantIdRoute,
}

const MaterialsRouteWithChildren = MaterialsRoute._addFileChildren(
  MaterialsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CopilotRoute: CopilotRoute,
  MaterialsRoute: MaterialsRouteWithChildren,
  RecommendationsRoute: RecommendationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
